cursos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cursos, name="cursos"),
    path('materias/<int:id_curso>/', views.materia, name="materias"),
]

informacion/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.informacion, name="Informacion"),
    path('categoria/<int:categoria_id>/', views.categoria, name="Categoria"),
    path('post/<int:post_id>/', views.post, name="post"),
]

sitio_web/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from sitio_web import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('servicios.urls')),
    path('cursos/', include('cursos.urls')),
     path('promociones/', include('promociones.urls')),    
    path('informacion/', include('informacion.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name="logout"),
    path('', include('sitio_web_app.urls')),
]

informacion/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):

    nombre = models.CharField(max_length=50) 

    created = models.DateField(auto_now_add=True)

    update = models.DateField(auto_now_add=True)

    class Meta():
        verbose_name = "categoria"
        verbose_name_plural = "categorias"

    def __str__(self):
        return self.nombre

class Post(models.Model):
    titulo = models.CharField(max_length=40) 

    contenido = models.TextField()

    imagen = models.ImageField(upload_to="post", null=True, blank=True)

    autor = models.ForeignKey(User, on_delete = models.CASCADE)

    created = models.DateField(auto_now_add=True)

    categorias = models.ManyToManyField(Categoria)

    update = models.DateField(auto_now_add=True)

    class Meta():
        verbose_name = "post"
        verbose_name_plural = "posts"

    def __str__(self):
        return self.titulo

class Comentario(models.Model):

    contenido = models.TextField(max_length=50) 

    autor = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True )

    created = models.DateField(auto_now_add=True)

    id_post = models.IntegerField(null=True, blank=True )

    class Meta():
        verbose_name = "comentario"
        verbose_name_plural = "comentarios"


    def __str__(self):
        return self.contenido

informacion/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Comentario

class ComentarioFrom(forms.ModelForm):


    class Meta():

        model = Comentario

        fields = ['contenido', 'autor']

informacion/views.py
from django.shortcuts import render, redirect
from informacion.models import Post, Categoria, Comentario
from informacion.forms import ComentarioFrom
# Create your views here.

def informacion(request):

    titulo = "blog"

    categoria = Categoria.objects.all()

    post = Post.objects.all()

    return render(request, "informacion/blog.html", {"titulo":titulo, "post":post, "categoria":categoria,})


def categoria(request, categoria_id):

    titulo = "categoria"

    id_categoria = Categoria.objects.get(id=categoria_id)

    post = Post.objects.filter(categorias=id_categoria)

    categorias = Categoria.objects.all()

    return render(request, "informacion/categoria.html", {"categoria_id":id_categoria, "post":post,"titulo":titulo, "categoria":categorias, })


def post(request, post_id):
    
    if request.method == "POST":
        ide = request.user
        contenido = request.POST['contenido']
        p = Comentario(contenido=contenido, autor=ide, id_post=post_id)
        p.save()

    comentarios = Comentario.objects.filter(id_post=post_id).order_by('-created')
    formu = ComentarioFrom()
    post = Post.objects.get(id=post_id)
    
    return render(request, "informacion/post.html", {"post":post,"titulo":post.titulo,"from":formu, "comentarios":comentarios})

informacion/templates/informacion/blog.html
{% extends "sitio_web_app/base.html" %}
{% load static %}
{% block content %}

    <section>

        <div class="informacion">

            <div class="informacion-div">
                
                <b> categorias: &nbsp;</b>
                
                {% for categoria in categoria%}

                        <a class="informacion-div-a" href="categoria/{{categoria.id}}/">
                    
                            {{categoria.nombre}}
                        
                        </a>
                        /
                {% endfor %}
            
            </div>

        </div>

    </section>

    <div class="container">
        
        <div class="row">

            {% for post in post %}
                
                <div class="col-sm-6 col-lg-4 mx-auto">


                            <div class="card bg my-5 col-12" >
                                <img class="card-img-top blog-img" src="{{post.imagen.url}}" alt="">
                                <div class="card-body text-truncat">
                                  <h5 class="card-title">{{post.titulo}}</h5>
                                  <h6 class="card-subtitle mb-2 text-muted">autor: {{post.autor}}</h6>
                                  <p class="card-text">{{post.contenido|slice:'60'|lower}}...</p>
                                  <a href="post/{{post.id}}/#titulo" class="btn btn-primary">Ver mas...</a>
                                </div>
                              </div>

                       
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

informacion/templates/informacion/categoria.html
{% extends "sitio_web_app/base.html" %}
{% load static %}
{% block content %}

    <section>

        <div class="informacion">

            <div class="informacion-div">

                <b> categorias: &nbsp;</b>
                
                {% for categoria in categoria%}

                    <a class="informacion-div-a" href="../../categoria/{{categoria.id}}/">

                        {{categoria.nombre}}
                        
                    </a>
                    /
                    
                {% endfor %}

            </div>

        </div>

    </section>


    <div class="container">
        
        <div class="row">

            {% for post in post %}
                
                <div class="col-sm-4 col-lg-4 col-xl-5">

                    <div class="blog align-items-center">
            
                        <div class="blog-text left-0 text-left bg-faded p-5 rounded">

                            <img class="blog-img img-thumbnail mb-3 mb-lg-0 rounded mx-auto d-block w3-card-4" src="{{post.imagen.url}}" alt=""> 
                
                            <h2 class="section-heading mb-4" >

                                <p class="section-heading-lower" style="text-align: center; font-size: 0.9em;">{{post.titulo}}</p>

                            </h2>

                            <p class="mb-3" style="text-align: center; font-size: 1em;">{{post.contenido}} </p>
                
                            <div style="text-align: left; font-size: 0.8em;" >
                    
                                post: {{post.autor}}
                    
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

informacion/templates/informacion/post.html
{% extends "sitio_web_app/base.html" %}
{% load static %}
{% block content %}


<section>

</section>

        <div class="col-sm-10 col-lg-11 mx-auto my-5 p-0 m-0">
            <div class="card trasparente">
                <div class="card-body m-0 p-0" style="margin: 10px;">

                        <div id="titulo"class="card-header card-title post-titulo">
                            
                            {{post.titulo}}
                            
                        </div>

                        <img class="post-img" src="{{post.imagen.url}}" alt="Card image cap">
                        <div class="card-text post-contenido text-left">
                            {{post.contenido|linebreaks }}
                        </div>

                        
                    </div>
      
                  
                </div>
            </div>
        </div>


        <div class="col-sm-10 col-lg-11 mx-auto my-5 p-2 m-0 comentario trasparente"> 
            {% if user.is_authenticated %}
            <div class="comentario-form">
                <div class="title my-3 cometario-title" style="text-align: center;">

                    <h2>comentarios</h2>

                </div>

                    <form action="" method="POST"> {% csrf_token %}


                        <div class="form-group row comentario-grup mx-auto">

                            <textarea name="contenido" class="form-control" id="id_contenido" placeholder="escribe un comentario:" style="width: 75%; height: 60px;"></textarea>
                        
                            <button type="submit" class="btn btn-primary"> Enviar </button>

                        </div>
                    </form>

            </div>
        {% else %}


            <div class="card-header">
                <div class="list-group-item mb-4">
                    <p class="mx-4">
                        ¿desea dejar su comentario? <a href="{% url 'login'%}"> <b>inicie sesion.</b> </a> <br>
                        ¿o es tu primera ves por aqui? entonces registra de forma gratuita haciendo click<a href="{% url 'registro'%}"><b> aqui </b></a>
                    </p>
                </div>
            </div>

        {% endif %}

        {% for comentarios in comentarios %}

            <div class="">

                <p class="h4">{{comentarios.autor}}: </p> 

                <div class="list-group-item mb-4">

                    {{comentarios}}

                </div>
            
            </div>
            
        {% endfor %}
        </div>
{% endblock%}